name: finrem-cron
description: Financial Remedy cron jobs
home: https://github.com/hmcts/finrem-cron
apiVersion: v2
appVersion: "1.0"
version: 0.0.20
maintainers:
  - name: HMCTS Financial Remedy Team
dependencies:
  - name: job
    version: 1.1.5
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
